[project]
name = "starlette-minimal"
version = "1.6.0"
authors = [
    { name = "Alpha", email = "dev@alpha93.kr" }
]
requires-python = ">=3.13"
dependencies = [
    "alpha93>=1.2.2",
    "anyio>=4.0.0,<5",
    "typing_extensions>=4.10.0; python_version < '3.13'",
]

[dependency-groups]
dev = [
    "alpha93-stubs>=1.2.2",
    "basedpyright>=1.40.1",
    "makepatch",
    "mypy>=2.3.1",
    "ruff>=0.16.8",
    "ty>=0.0.83",
]

[tool.uv.sources]
makepatch = { git = "ssh://git@github.com/MadeByAlpha/makepatch.git" }

[build-system]
requires = [
    "hatchling",
    "makepatch @ git+ssh://git@github.com/MadeByAlpha/makepatch.git",
]
build-backend = "hatchling.build"

[tool.hatch.build.hooks.makepatch]
[tool.hatch.build.targets.wheel]
packages = ["src/alpha93"]

[tool.makepatch.source]
upstream = "https://github.com/Kludex/starlette.git"
ref = "1.6.0"
include = { "starlette" = "starlette" }
exclude = [
]
work-exclude = [
    ".github/",
    "benchmarks/",
    "docs/",
    "scripts/",
    "starlette/middleware/sessions.py",
    "starlette/middleware/wsgi.py",
    "starlette/config.py",
    "starlette/endpoints.py",
    "starlette/schemas.py",
    "starlette/templating.py",
    "starlette/testclient.py",
    "tests/",
    ".gitignore",
    "CITATION.cff",
    "mkdocs.yml",
    "pyproject.toml",
    "uv.lock",
    "wrangler.toml",
]

[tool.ruff]
line-length = 120

[tool.ty.environment]
root = [
    "./typings",
    "./src",
    "./work"
]
