"""
This type stub file was generated by pyright.
"""

from collections.abc import AsyncGenerator, Awaitable, Callable, Generator
from contextlib import AbstractAsyncContextManager, asynccontextmanager
from dataclasses import dataclass
from typing import Any, Protocol, TypeIs, TypeVar, overload

import anyio.abc

from starlette.types import Scope

T = TypeVar("T")
type AwaitableCallable[T] = Callable[..., Awaitable[T]]
_HOST_RE = ...
@dataclass(frozen=True, slots=True)
class ParsedHost:
    host: str
    port: str | None
    @property
    def authority(self) -> str:
        ...
    
    @property
    def is_valid_port(self) -> bool:
        ...
    


@overload
def is_async_callable[T](obj: AwaitableCallable[T]) -> TypeIs[AwaitableCallable[T]]:
    ...

@overload
def is_async_callable(obj: Any) -> TypeIs[AwaitableCallable[Any]]:
    ...

def is_async_callable(obj: Any) -> Any:
    ...

T_co = TypeVar("T_co", covariant=True)
class AwaitableOrContextManager(Awaitable[T_co], AbstractAsyncContextManager[T_co], Protocol[T_co]):
    ...


class SupportsAsyncClose(Protocol):
    async def close(self) -> None:
        ...
    


SupportsAsyncCloseType = TypeVar("SupportsAsyncCloseType", bound=SupportsAsyncClose, covariant=False)
class AwaitableOrContextManagerWrapper[SupportsAsyncCloseType: SupportsAsyncClose]:
    __slots__ = ...
    def __init__(self, aw: Awaitable[SupportsAsyncCloseType]) -> None:
        ...
    
    def __await__(self) -> Generator[Any, None, SupportsAsyncCloseType]:
        ...
    
    async def __aenter__(self) -> SupportsAsyncCloseType:
        ...
    
    async def __aexit__(self, *args: object) -> bool | None:
        ...
    


@asynccontextmanager
async def create_collapsing_task_group() -> AsyncGenerator[anyio.abc.TaskGroup]:
    ...

def parse_host_header(host_header: str | None) -> ParsedHost | None:
    """Parse `host_header` into its host and port components.

    The host preserves brackets around IP literals. Invalid headers produce `None`.
    """

def get_route_path(scope: Scope) -> str:
    ...

