"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable, Sequence
from typing import Any, ParamSpec

P = ParamSpec("P")
class BackgroundTask:
    def __init__(self, func: Callable[P, Any], *args: P.args, **kwargs: P.kwargs) -> None:
        ...
    
    async def __call__(self) -> None:
        ...
    


class BackgroundTasks(BackgroundTask):
    def __init__(self, tasks: Sequence[BackgroundTask] | None = ...) -> None:
        ...
    
    def add_task(self, func: Callable[P, Any], *args: P.args, **kwargs: P.kwargs) -> None:
        ...
    
    async def __call__(self) -> None:
        ...
    


