"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable, Iterator, Mapping, MutableMapping
from pathlib import Path
from typing import Any, TypeVar, overload

class undefined:
    ...


class EnvironError(Exception):
    ...


class Environ(MutableMapping[str, str]):
    def __init__(self, environ: MutableMapping[str, str] = ...) -> None:
        ...
    
    def __getitem__(self, key: str) -> str:
        ...
    
    def __setitem__(self, key: str, value: str) -> None:
        ...
    
    def __delitem__(self, key: str) -> None:
        ...
    
    def __iter__(self) -> Iterator[str]:
        ...
    
    def __len__(self) -> int:
        ...
    


environ = ...
T = TypeVar("T")
class Config:
    def __init__(self, env_file: str | Path | None = ..., environ: Mapping[str, str] = ..., env_prefix: str = ..., encoding: str = ...) -> None:
        ...
    
    @overload
    def __call__(self, key: str, *, default: None) -> str | None:
        ...
    
    @overload
    def __call__(self, key: str, cast: type[T], default: T = ...) -> T:
        ...
    
    @overload
    def __call__(self, key: str, cast: type[str] = ..., default: str = ...) -> str:
        ...
    
    @overload
    def __call__(self, key: str, cast: Callable[[Any], T] = ..., default: Any = ...) -> T:
        ...
    
    @overload
    def __call__(self, key: str, cast: type[str] = ..., default: T = ...) -> T | str:
        ...
    
    def __call__(self, key: str, cast: Callable[[Any], Any] | None = ..., default: Any = ...) -> Any:
        ...
    
    def get(self, key: str, cast: Callable[[Any], Any] | None = ..., default: Any = ...) -> Any:
        ...
    


