"""
This type stub file was generated by pyright.
"""

from collections.abc import Mapping

class HTTPException(Exception):
    def __init__(self, status_code: int, detail: str | None = ..., headers: Mapping[str, str] | None = ...) -> None:
        ...
    
    
    


class WebSocketException(Exception):
    def __init__(self, code: int, reason: str | None = ...) -> None:
        ...
    
    
    


class StarletteDeprecationWarning(UserWarning):
    """A custom deprecation warning for Starlette.

    Unlike the built-in DeprecationWarning, this inherits from UserWarning to ensure it is visible by default, helping
    users discover deprecated features without needing to enable warnings explicitly.

    Reference: https://sethmlarson.dev/deprecations-via-warnings-dont-work-for-python-libraries
    """


