"""
This type stub file was generated by pyright.
"""
from abc import ABC, abstractmethod
from collections.abc import Awaitable, Callable, Collection, Sequence
from enum import Enum, auto
from re import Pattern
from typing import Any, Protocol, override

from starlette.convertors import Convertor
from starlette.datastructures import URLPath
from starlette.middleware import Middleware
from starlette.requests import Request
from starlette.responses import Response
from starlette.types import ASGIApp, ASGIAppType, Lifespan, Receive, Scope, Send
from starlette.websockets import WebSocket

# <editor-fold defaultstate="collapsed" desc="enum Match">
class Match(Enum):
    NONE = 0
    PARTIAL = auto()
    FULL = auto()

class NoMatchFound(Exception):
    """
    Raised by `.url_for(name, **path_params)` and `.url_path_for(name, **path_params)`
    if no matching route exists.
    """
    def __init__(self, name: str, path_params: dict[str, Any]) -> None:
        ...
# </editor-fold>

# <editor-fold defaultstate="collapsed" desc="methods">
# def request_response(func: Callable[[Request], Awaitable[Response] | Response]) -> ASGIApp:
#     """
#     Takes a function or coroutine `func(request) -> response`,
#     and returns an ASGI application.
#     """
#
# def websocket_session(func: Callable[[WebSocket], Awaitable[None]]) -> ASGIApp:
#     """
#     Takes a coroutine `func(session)`, and returns an ASGI application.
#     """
#
# def get_name(endpoint: Callable[..., Any]) -> str:
#     ...

def replace_params(path: str, param_convertors: dict[str, Convertor[Any]], path_params: dict[str, str]) -> tuple[str, dict[str, str]]:
    ...

def compile_path(path: str) -> tuple[Pattern[str], str, dict[str, Convertor[Any]]]:
    """
    Given a path string, like: "/{username:str}",
    or a host string, like: "{subdomain}.mydomain.org", return a three-tuple
    of (regex, format, {param_name:convertor}).

    regex:      "/(?P<username>[^/]+)"
    format:     "/{username}"
    convertors: {"username": StringConvertor()}
    """
# </editor-fold>

class BaseRoute(ABC, ASGIAppType):
    def matches(self, scope: Scope) -> tuple[Match, Scope]:
        ...

    def url_path_for(self, name: str, /, **path_params: Any) -> URLPath:
        ...

    async def handle(self, scope: Scope, receive: Receive, send: Send) -> None:
        ...

    @override
    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        """
        A route may be used in isolation as a stand-alone ASGI app.
        This is a somewhat contrived case, as they'll almost always be used
        within a Router, but could be useful for some tooling and minimal apps.
        """

class RouterMixin(Routes, ABC):
    ...

class AttachableRoute[T: RouterMixin](BaseRoute, ABC):
    ...

class RouteAttachMixin(RouterMixin, ABC):
    def add_route(self, path: str, endpoint: Callable[[Request], Awaitable[Response] | Response], methods: Collection[str] | None = ..., name: str | None = ..., include_in_schema: bool = ...) -> None:
        ...

class Route(AttachableRoute[RouteAttachMixin]):
    def __init__(self, path: str, endpoint: Callable[..., Any], *, methods: Collection[str] | None = ..., name: str | None = ..., include_in_schema: bool = ..., middleware: Sequence[Middleware] | None = ..., max_body_size: int | None = ...) -> None:
        ...

    @override
    def matches(self, scope: Scope) -> tuple[Match, Scope]:
        ...

    @override
    def url_path_for(self, name: str, /, **path_params: Any) -> URLPath:
        ...

    @override
    async def handle(self, scope: Scope, receive: Receive, send: Send) -> None:
        ...

    def __eq__(self, other: object) -> bool:
        ...

class WebSocketRouteAttachMixin(RouterMixin, ABC):
    def add_websocket_route(self, path: str, endpoint: Callable[[WebSocket], Awaitable[None]], name: str | None = ...) -> None:
        ...

class WebSocketRoute(AttachableRoute[WebSocketRouteAttachMixin]):
    def __init__(self, path: str, endpoint: Callable[..., Any], *, name: str | None = ..., middleware: Sequence[Middleware] | None = ...) -> None:
        ...

    @override
    def matches(self, scope: Scope) -> tuple[Match, Scope]:
        ...

    @override
    def url_path_for(self, name: str, /, **path_params: Any) -> URLPath:
        ...

    @override
    async def handle(self, scope: Scope, receive: Receive, send: Send) -> None:
        ...

    def __eq__(self, other: object) -> bool:
        ...

class Routes(Protocol):
    @property
    def routes(self) -> list[BaseRoute]:
        ...

class ApplicationRoute[T: RouterMixin](AttachableRoute[T], ABC, Routes):
    ...

class MountMixin(RouterMixin, ABC):
    def mount(self, path: str, app: ASGIApp, name: str | None = ...) -> None:
        ...

class Mount(ApplicationRoute[MountMixin]):
    def __init__(self, path: str, app: ASGIApp | None = ..., routes: Sequence[BaseRoute] | None = ..., name: str | None = ..., *, middleware: Sequence[Middleware] | None = ..., max_body_size: int | None = ...) -> None:
        ...

    @override
    @property
    def routes(self) -> list[BaseRoute]:
        ...

    @override
    def matches(self, scope: Scope) -> tuple[Match, Scope]:
        ...

    @override
    def url_path_for(self, name: str, /, **path_params: Any) -> URLPath:
        ...

    @override
    async def handle(self, scope: Scope, receive: Receive, send: Send) -> None:
        ...

    def __eq__(self, other: object) -> bool:
        ...

class HostMixin(RouterMixin, ABC):
    def host(self, host: str, app: ASGIApp, name: str | None = ...) -> None:
        ...

class Host(ApplicationRoute[HostMixin]):
    def __init__(self, host: str, app: ASGIApp, name: str | None = ...) -> None:
        ...

    @override
    @property
    def routes(self) -> list[BaseRoute]:
        ...

    @override
    def matches(self, scope: Scope) -> tuple[Match, Scope]:
        ...

    @override
    def url_path_for(self, name: str, /, **path_params: Any) -> URLPath:
        ...

    @override
    async def handle(self, scope: Scope, receive: Receive, send: Send) -> None:
        ...

    def __eq__(self, other: object) -> bool:
        ...

class Routable(
    RouteAttachMixin,
    WebSocketRouteAttachMixin,
    MountMixin,
    HostMixin,
    Routes,
    ABC,
    ASGIAppType,
):
    @abstractmethod
    def url_path_for(self, name: str, /, **path_params: Any) -> URLPath:
        ...

class Router(Routable):
    redirect_slashes: bool
    default: ASGIApp
    lifespan_context: Lifespan[Any]
    middleware_stack: ASGIApp

    def __init__(
        self,
        routes: Sequence[BaseRoute] | None = ...,
        redirect_slashes: bool = ...,
        default: ASGIApp | None = ...,
        lifespan: Lifespan[Any] | None = ...,
        *,
        middleware: Sequence[Middleware] | None = ...,
        max_body_size: int | None = ...,
    ) -> None: ...
    async def not_found(self, scope: Scope, receive: Receive, send: Send) -> None: ...
    async def lifespan(self, scope: Scope, receive: Receive, send: Send) -> None:
        """
        Handle ASGI lifespan messages, which allows us to manage application
        startup and shutdown events.
        """

    async def app(self, scope: Scope, receive: Receive, send: Send) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    @override
    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        """
        The main entry point to the Router class.
        """

    @override
    def url_path_for(self, name: str, /, **path_params: Any) -> URLPath: ...
