"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable
from typing import Any, NamedTuple

from starlette.requests import Request
from starlette.responses import Response
from starlette.routing import BaseRoute

class OpenAPIResponse(Response):
    media_type = ...
    def render(self, content: Any) -> bytes:
        ...
    


class EndpointInfo(NamedTuple):
    path: str
    http_method: str
    func: Callable[..., Any]


_remove_converter_pattern = ...
class BaseSchemaGenerator:
    def get_schema(self, routes: list[BaseRoute]) -> dict[str, Any]:
        ...
    
    def get_endpoints(self, routes: list[BaseRoute]) -> list[EndpointInfo]:
        """
        Given the routes, yields the following information:

        - path
            eg: /users/
        - http_method
            one of 'get', 'post', 'put', 'patch', 'delete', 'options', 'query'
        - func
            method ready to extract the docstring
        """
    
    def parse_docstring(self, func_or_method: Callable[..., Any]) -> dict[str, Any]:
        """
        Given a function, parse the docstring as YAML and return a dictionary of info.
        """
    
    def OpenAPIResponse(self, request: Request) -> Response:
        ...
    


class SchemaGenerator(BaseSchemaGenerator):
    def __init__(self, base_schema: dict[str, Any]) -> None:
        ...
    
    def get_schema(self, routes: list[BaseRoute]) -> dict[str, Any]:
        ...
    


