"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable, Mapping, Sequence
from os import PathLike
from typing import TYPE_CHECKING, Any, overload

import jinja2

from starlette.background import BackgroundTask
from starlette.requests import Request
from starlette.responses import HTMLResponse
from starlette.types import Receive, Scope, Send

if TYPE_CHECKING:
    pass_context = ...
class _TemplateResponse(HTMLResponse):
    def __init__(self, template: Any, context: dict[str, Any], status_code: int = ..., headers: Mapping[str, str] | None = ..., media_type: str | None = ..., background: BackgroundTask | None = ...) -> None:
        ...
    
    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        ...
    


class Jinja2Templates:
    """Jinja2 template renderer.

    Example:
        ```python
        from starlette.templating import Jinja2Templates

        templates = Jinja2Templates(directory="templates")

        async def homepage(request: Request) -> Response:
            return templates.TemplateResponse(request, "index.html")
        ```
    """
    @overload
    def __init__(self, directory: str | PathLike[str] | Sequence[str | PathLike[str]], *, context_processors: list[Callable[[Request], dict[str, Any]]] | None = ...) -> None:
        ...
    
    @overload
    def __init__(self, *, env: jinja2.Environment, context_processors: list[Callable[[Request], dict[str, Any]]] | None = ...) -> None:
        ...
    
    def __init__(self, directory: str | PathLike[str] | Sequence[str | PathLike[str]] | None = ..., *, context_processors: list[Callable[[Request], dict[str, Any]]] | None = ..., env: jinja2.Environment | None = ...) -> None:
        ...
    
    def get_template(self, name: str) -> jinja2.Template:
        ...
    
    def TemplateResponse(self, request: Request, name: str, context: dict[str, Any] | None = ..., status_code: int = ..., headers: Mapping[str, str] | None = ..., media_type: str | None = ..., background: BackgroundTask | None = ...) -> _TemplateResponse:
        """
        Render a template and return an HTML response.

        Args:
            request: The incoming request instance.
            name: The template file name to render.
            context: Variables to pass to the template.
            status_code: HTTP status code for the response.
            headers: Additional headers to include in the response.
            media_type: Media type for the response.
            background: Background task to run after response is sent.

        Returns:
            An HTML response with the rendered template content.
        """
    


