"""
This type stub file was generated by pyright.
"""

from collections.abc import Awaitable, Callable, Iterable, Mapping, Sequence
from concurrent.futures import Future
from contextlib import AbstractContextManager
from typing import TYPE_CHECKING, Any, Literal, Self, TypedDict

import anyio.from_thread
import httpx2 as httpx

from starlette.types import ASGIApp, Message, Receive, Scope, Send
from starlette.websockets import WebSocketDisconnect

if TYPE_CHECKING:
    ...
type _PortalFactoryType = Callable[[], AbstractContextManager[anyio.from_thread.BlockingPortal]]
type ASGIInstance = Callable[[Receive, Send], Awaitable[None]]
type ASGI2App = Callable[[Scope], ASGIInstance]
type ASGI3App = Callable[[Scope, Receive, Send], Awaitable[None]]
type _RequestData = Mapping[str, str | Iterable[str] | bytes]
class _WrapASGI2:
    """
    Provide an ASGI3 interface onto an ASGI2 app.
    """
    def __init__(self, app: ASGI2App) -> None:
        ...
    
    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        ...
    


class _AsyncBackend(TypedDict):
    backend: str
    backend_options: dict[str, Any]


class _Upgrade(Exception):
    def __init__(self, session: WebSocketTestSession) -> None:
        ...
    


class WebSocketDenialResponse(httpx.Response, WebSocketDisconnect):
    """
    A special case of `WebSocketDisconnect`, raised in the `TestClient` if the
    `WebSocket` is closed before being accepted with a `send_denial_response()`.
    """


class WebSocketTestSession:
    def __init__(self, app: ASGI3App, scope: Scope, portal_factory: _PortalFactoryType) -> None:
        ...
    
    def __enter__(self) -> Self:
        ...
    
    def __exit__(self, *args: object) -> bool | None:
        ...
    
    def send(self, message: Message) -> None:
        ...
    
    def send_text(self, data: str) -> None:
        ...
    
    def send_bytes(self, data: bytes) -> None:
        ...
    
    def send_json(self, data: Any, mode: Literal["text", "binary"] = ...) -> None:
        ...
    
    def close(self, code: int = ..., reason: str | None = ...) -> None:
        ...
    
    def receive(self) -> Message:
        ...
    
    def receive_text(self) -> str:
        ...
    
    def receive_bytes(self) -> bytes:
        ...
    
    def receive_json(self, mode: Literal["text", "binary"] = ...) -> Any:
        ...
    


class _TestClientTransport(httpx.BaseTransport):
    def __init__(self, app: ASGI3App, portal_factory: _PortalFactoryType, raise_server_exceptions: bool = ..., root_path: str = ..., *, client: tuple[str, int], app_state: dict[str, Any]) -> None:
        ...
    
    def handle_request(self, request: httpx.Request) -> httpx.Response:
        ...
    


class TestClient(httpx.Client):
    __test__ = ...
    task: Future[None]
    portal: anyio.from_thread.BlockingPortal | None = ...
    def __init__(self, app: ASGIApp, base_url: str = ..., raise_server_exceptions: bool = ..., root_path: str = ..., backend: Literal["asyncio", "trio"] = ..., backend_options: dict[str, Any] | None = ..., cookies: httpx._types.CookieTypes | None = ..., headers: dict[str, str] | None = ..., follow_redirects: bool = ..., client: tuple[str, int] = ...) -> None:
        ...
    
    def request(self, method: str, url: httpx._types.URLTypes, *, content: httpx._types.RequestContent | None = ..., data: _RequestData | None = ..., files: httpx._types.RequestFiles | None = ..., json: Any = ..., params: httpx._types.QueryParamTypes | None = ..., headers: httpx._types.HeaderTypes | None = ..., cookies: httpx._types.CookieTypes | None = ..., auth: httpx._types.AuthTypes | httpx._client.UseClientDefault = ..., follow_redirects: bool | httpx._client.UseClientDefault = ..., timeout: httpx._types.TimeoutTypes | httpx._client.UseClientDefault = ..., extensions: dict[str, Any] | None = ...) -> httpx.Response:
        ...
    
    def websocket_connect(self, url: str, subprotocols: Sequence[str] | None = ..., **kwargs: Any) -> WebSocketTestSession:
        ...
    
    def __enter__(self) -> Self:
        ...
    
    def __exit__(self, *args: object) -> None:
        ...
    
    async def lifespan(self) -> None:
        ...
    
    async def wait_startup(self) -> None:
        ...
    
    async def wait_shutdown(self) -> None:
        ...
    


