"""
This type stub file was generated by pyright.
"""

from collections.abc import Awaitable, Callable, Mapping, MutableMapping
from contextlib import AbstractAsyncContextManager
from typing import TYPE_CHECKING, Any, TypeVar

from starlette.requests import Request
from starlette.responses import Response
from starlette.websockets import WebSocket

if TYPE_CHECKING:
    ...
AppType = TypeVar("AppType")
type Scope = MutableMapping[str, Any]
type Message = MutableMapping[str, Any]
type Receive = Callable[[], Awaitable[Message]]
type Send = Callable[[Message], Awaitable[None]]
type ASGIApp = Callable[[Scope, Receive, Send], Awaitable[None]]
type StatelessLifespan[AppType] = Callable[[AppType], AbstractAsyncContextManager[None]]
type StatefulLifespan[AppType] = Callable[[AppType], AbstractAsyncContextManager[Mapping[str, Any]]]
type Lifespan[AppType] = StatelessLifespan[AppType] | StatefulLifespan[AppType]
type HTTPExceptionHandler = Callable[[Request, Exception], Response | Awaitable[Response]]
type WebSocketExceptionHandler = Callable[[WebSocket, Exception], Awaitable[None]]
type ExceptionHandler = HTTPExceptionHandler | WebSocketExceptionHandler
