"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable

from starlette.authentication import AuthenticationBackend, AuthenticationError
from starlette.requests import HTTPConnection
from starlette.responses import Response
from starlette.types import ASGIApp, Receive, Scope, Send

class AuthenticationMiddleware:
    def __init__(self, app: ASGIApp, backend: AuthenticationBackend, on_error: Callable[[HTTPConnection, AuthenticationError], Response] | None = ...) -> None:
        ...
    
    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        ...
    
    @staticmethod
    def default_on_error(conn: HTTPConnection, exc: Exception) -> Response:
        ...
    


