"""
This type stub file was generated by pyright.
"""

from collections.abc import (
    AsyncGenerator,
    AsyncIterable,
    Awaitable,
    Callable,
    Mapping,
    MutableMapping,
)
from typing import Any, TypeVar

from starlette.requests import Request
from starlette.responses import Response
from starlette.types import ASGIApp, Message, Receive, Scope, Send

type RequestResponseEndpoint = Callable[[Request], Awaitable[Response]]
type DispatchFunction = Callable[[Request, RequestResponseEndpoint], Awaitable[Response]]
type BodyStreamGenerator = AsyncGenerator[bytes | MutableMapping[str, Any]]
type AsyncContentStream = AsyncIterable[str | bytes | memoryview | MutableMapping[str, Any]]
T = TypeVar("T")
class _CachedRequest(Request):
    """
    If the user calls Request.body() from their dispatch function
    we cache the entire request body in memory and pass that to downstream middlewares,
    but if they call Request.stream() then all we do is send an
    empty body so that downstream things don't hang forever.
    """
    def __init__(self, scope: Scope, receive: Receive) -> None:
        ...
    
    async def wrapped_receive(self) -> Message:
        ...
    


class BaseHTTPMiddleware:
    def __init__(self, app: ASGIApp, dispatch: DispatchFunction | None = ...) -> None:
        ...
    
    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        ...
    
    async def dispatch(self, request: Request, call_next: RequestResponseEndpoint) -> Response:
        ...
    


class _StreamingResponse(Response):
    def __init__(self, content: AsyncContentStream, status_code: int = ..., headers: Mapping[str, str] | None = ..., media_type: str | None = ..., info: Mapping[str, Any] | None = ...) -> None:
        ...
    
    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        ...
    


