"""
This type stub file was generated by pyright.
"""

from starlette.exceptions import HTTPException
from starlette.types import ASGIApp, Message, Receive, Scope, Send

MAX_BODY_SIZE_SCOPE_KEY = ...
_BODY_LIMIT_RESPONDER_SCOPE_KEY = ...
class _Missing:
    __slots__ = ...


_MISSING = ...
class _RequestBodyTooLarge(HTTPException):
    def __init__(self) -> None:
        ...
    


class _RequestBodyLimitResponseSent(Exception):
    ...


class RequestBodyLimitMiddleware:
    """Limit the total size of an HTTP request body."""
    def __init__(self, app: ASGIApp, max_body_size: int) -> None:
        ...
    
    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        ...
    


class RequestBodyLimitResponder:
    def __init__(self, app: ASGIApp, max_body_size: int) -> None:
        ...
    
    @property
    def scope(self) -> Scope:
        ...
    
    @property
    def receive(self) -> Receive:
        ...
    
    @property
    def send(self) -> Send:
        ...
    
    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        ...
    
    async def receive_with_limit(self) -> Message:
        ...
    
    async def send_with_limit(self, message: Message) -> None:
        ...
    


